### ISSUE TITLE
Estructurar archivo CSS

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#11]
En al archivo CSS se debe estructurar y dar estilos a los siguientes apartados:

- [x] Home
- [x] Barra de Menu
- [x] Dar estilos al HTML de Popular Drinks
- [x] Dar estilos al HTML de Popular Ingredients
- [x] Dar estilos al HTML de Latest Drinks
- [x] Dar estilos al HTML de Random Ingredients
- [x] Dar estilos al HTML de Random Drinks
- [x] Pagination

**Comment by 8devmx** [comment]
¿Por qué no está asignado?

**Comment by 8devmx** [comment]
Fecha de entrega: Martes 4 de Julio

Assignes: Miguel

**Comment by miguel-ivan** [comment]
se le dio estilos a los HTML
