### ISSUE TITLE
Crear JSON

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#3]
- [x] Dentro de la carpeta principal crear una segunda carpeta llamada JSON
- [x]  Dentro de la carpeta JSON crear un archivo llamado JSON con terminación js

**Comment by 8devmx** [comment]
Fecha de entrega: 27 de Junio

**Comment by Carlos-Arizmendi** [comment]
Se creó carpeta JSON.
