### ISSUE TITLE
Empezar a estructurar documento HTML y enlazar documentos externos

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#4]
- [x]  En el documento index.html generar la estructura básica de HTML
- [x]  Enlazar hoja styles.css a la estructura de HTML
- [x]  Al final de la estructura enlazar hoja json.js

**Comment by 8devmx** [comment]
Fecha de entrega: Martes 27 de Junio

**Comment by miguel-ivan** [comment]
ya se enlazo los dos documentos
