### ISSUE TITLE
Crear menu de página

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#5]
- [x] Agregar titulo de la página

Crear barra de menu con las siguientes opciones:
- [x] Home
- [x] Popular Drinks
- [x] Popular Ingredients
- [x] Latest Drinks
- [x] Random Ingredients
- [x] Random Drinks

**Comment by 8devmx** [comment]
¿Por qué no se ha cerrado este Issue?
Por qué sigue en todo?

**Comment by miguel-ivan** [comment]
ya se termino el menu con todas sus ventanas
