### ISSUE TITLE
Editar pagina Home

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#6]
En la pagina home debe aparecer:

- [x] #12
- [x] Descripción de la pagina
- [x] Imágenes de las opciones de menú con enlace a su descripción
- [x] Contacto
- [x] Pagination

**Comment by 8devmx** [comment]
Fecha de entrega: Martes 27 de Junio

**Comment by miguel-ivan** [comment]
Se edito todo lo pedido en home
