### ISSUE TITLE
Crear documentos HTML de cada opción de menu

### ISSUE THREAD

**Issue by GleziDamaris** [miguel-ivan/drinks-segundo.parcial#7]
- [x] Crear documento html de Popular Drinks
- [x]  Crear documento html de Popular Ingredients
- [x] Crear documento html de Latest Drinks
- [x] Crear documento html de Random Ingredients
- [x] Crear documento html de Random Drinks

- [x] Enlazar cada uno al index.html
- [x] Enlazar cada html creado a styles.css

**Comment by Carlos-Arizmendi** [comment]
Se crearon las vinculaciones y documentos para html, css y cada uno de los apartados del menú.

**Comment by 8devmx** [comment]
Por qué no se ha cerrado?

**Comment by miguel-ivan** [comment]
se crearon los documentod HTML pedidos
